### ISSUE TITLE
What is index.js?

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab-translate#3]
I would like to understand the JS-side extraction but only see a huge blob of minimized JS. Could we have some documentation on where it is coming from, please?

**Comment by goanpeca** [comment]
Hi @krassowski 

Sorry I have not had much time to continue this work. I will make a temporal `DOCS.md` to explain the workflow.

Long story short, index.js is https://www.npmjs.com/package/gettext-extract compiled with all dependencies as that single file (see https://github.com/vercel/ncc), so we can use it mor easily by installing nodejs.

This is needed to be able to parse `TSX` files specifically since babel only supports TS/JS, but not the X versions (used by react)

**Comment by krassowski** [comment]
I'm thinking that it might be safer to just install Node.js and specify this as a proper npm dependency so we get notified of any security updates, especially if this is going to run on CI. Plus it will be easier to understand. Happy to prepare a PR. What do you think?

**Comment by fcollonval** [comment]
Fixed in e5c4a2f0dff8feec5d8fb6cf3e00368622e1ecca
